# Generated by Django 6.1.1 on 2026-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_progress',
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
    ]
