# Generated by Django 6.1.1 on 2026-09-09 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
